source "https://rubygems.org"

gem "rails", "~> 8.0.2"
gem "puma", ">= 5.0"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "rack-cors"
gem "pg"
gem 'devise'
gem 'devise-jwt'
gem 'jsonapi-serializer'
gem 'cancancan'

group :test do
  gem 'rspec-rails', '~> 8.0.0'
  gem 'database_cleaner-active_record'
end

group :development, :test do
  gem 'byebug', '~> 9.0', '>= 9.0.6'

  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end
